# Generated by Django 3.2.2 on 2021-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jobseekermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekermodel',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
