# Generated by Django 3.2.2 on 2021-05-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_companymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('JOBSEEKER', 'JobSeeker')], default='JOBSEEKER', max_length=15),
            preserve_default=False,
        ),
    ]
