# Generated by Django 3.2.2 on 2021-05-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
