# Generated by Django 3.2.2 on 2021-05-28 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('role_responsibility', models.CharField(max_length=2000, null=True)),
                ('requirements', models.CharField(max_length=2000, null=True)),
                ('experience', models.CharField(max_length=30, null=True)),
                ('shift_timing', models.CharField(max_length=30, null=True)),
                ('package', models.CharField(max_length=40, null=True)),
                ('joining_date', models.CharField(max_length=30, null=True)),
                ('apply_last_date', models.DateField(null=True)),
                ('part_time', models.BooleanField()),
                ('no_of_opening', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('DONE_HIRING', 'Done Hiring')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companymodel')),
            ],
        ),
    ]
