# Generated by Django 3.2.2 on 2021-05-28 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_linguisticlanguagemodel_locationmodel_skillsmodel'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobmodel')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.skillsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='JobLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobmodel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.locationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='JobLinguisticLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobmodel')),
                ('laguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.linguisticlanguagemodel')),
            ],
        ),
    ]
