# Generated by Django 3.2.2 on 2021-05-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joblinguisticlanguagemodel_joblocationmodel_jobskillmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='gender',
            field=models.CharField(choices=[('BOTH', 'Male and Female both'), ('MALE', 'Male only'), ('FEMALE', 'Female only')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='JobWeeklyOffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=15, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobmodel')),
            ],
        ),
    ]
