# Generated by Django 3.2.2 on 2021-05-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210529_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='joining_date',
        ),
    ]
