# Generated by Django 3.2.2 on 2021-06-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobmodel_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='package',
            field=models.IntegerField(null=True),
        ),
    ]
